# Generated by Django 4.2 on 2023-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bullet_point_one', models.CharField(max_length=200)),
                ('bullet_point_two', models.CharField(max_length=200)),
                ('icon_box_one_title', models.CharField(max_length=200)),
                ('icon_box_one_description', models.TextField()),
                ('icon_box_two_title', models.CharField(max_length=200)),
                ('icon_box_two_description', models.TextField()),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
        ),
    ]
