# Generated by Django 4.2 on 2023-04-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='icon_box_one_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='icon_box_one_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='icon_box_two_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='icon_box_two_title',
        ),
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_boxes', to='app_lllsf.aboutus')),
            ],
        ),
    ]
