# Generated by Django 4.2 on 2023-04-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0005_remove_aboutus_icon_box_one_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bullet_point_one', models.CharField(max_length=100)),
                ('bullet_point_two', models.CharField(max_length=100)),
                ('icon_boxes', models.ManyToManyField(to='app_lllsf.iconbox')),
            ],
        ),
    ]
