# Generated by Django 4.2 on 2023-04-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0006_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='percent',
            field=models.IntegerField(default=100),
        ),
    ]
