# Generated by Django 4.2 on 2023-04-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0007_exercise_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='icon_boxes',
        ),
    ]
