# Generated by Django 4.2 on 2023-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0008_remove_exercise_icon_boxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
    ]
