# Generated by Django 4.2 on 2023-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
