# Generated by Django 4.2 on 2023-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0012_recipeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='category',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('lifestyle', 'Lifestyle')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='fitnessblogs/'),
        ),
    ]
