# Generated by Django 4.2 on 2023-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0013_category_fitnessblog_category_fitnessblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_5',
            field=models.TextField(blank=True),
        ),
    ]
