# Generated by Django 4.2 on 2023-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0014_fitnessblog_paragraph_1_fitnessblog_paragraph_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessblog',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='image_2',
            field=models.ImageField(default='default_image.jpg', upload_to='fitnessblogs/'),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessblog',
            name='paragraph_9',
            field=models.TextField(blank=True),
        ),
    ]
