# Generated by Django 4.2 on 2023-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0016_fitnessblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='paragraph_9',
            field=models.TextField(blank=True),
        ),
    ]
