# Generated by Django 4.2 on 2023-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0017_recipeitem_description_recipeitem_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='details_link',
        ),
    ]
