# Generated by Django 4.2 on 2023-05-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0018_remove_recipeitem_details_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessBlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.TextField()),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_lllsf.fitnessblogcomment')),
            ],
        ),
    ]
