# Generated by Django 4.2 on 2023-05-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0019_fitnessblogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessblogcomment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_lllsf.fitnessblog'),
        ),
    ]
