# Generated by Django 4.2 on 2023-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0020_fitnessblogcomment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_9',
            field=models.TextField(blank=True),
        ),
    ]
