# Generated by Django 4.2 on 2023-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0022_fitnessblog_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessblogcomment',
            name='icon',
            field=models.CharField(default='fa-light fa-user-astronaut', max_length=50),
        ),
    ]
