# Generated by Django 4.2 on 2023-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0023_fitnessblogcomment_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='image',
            new_name='image_finished',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='image_ingredients',
            field=models.ImageField(default='image_finished', upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='image_process',
            field=models.ImageField(default='image_finished', upload_to='portfolio_images/'),
        ),
    ]
