# Generated by Django 4.2 on 2023-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0025_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='imgs/about_us_images/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/exercises/'),
        ),
        migrations.AlterField(
            model_name='fitnessblog',
            name='image_1',
            field=models.ImageField(default='default_image.jpg', upload_to='imgs/fitnessblogs/'),
        ),
        migrations.AlterField(
            model_name='fitnessblog',
            name='image_2',
            field=models.ImageField(default='default_image.jpg', upload_to='imgs/fitnessblogs/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='imgs/hero_images/'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='image_finished',
            field=models.ImageField(upload_to='imgs/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='image_ingredients',
            field=models.ImageField(default='image_finished', upload_to='imgs/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='image_process',
            field=models.ImageField(default='image_finished', upload_to='imgs/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='imgs/testimonials/'),
        ),
    ]
