# Generated by Django 4.2 on 2023-05-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lllsf', '0030_service_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessblog',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
